apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: simple-quarkus-service
    app.kubernetes.io/name: simple-quarkus-service
    pipeline.openshift.io/runtime: java
    pipeline.openshift.io/runtime-version: openjdk-11-el7
    pipeline.openshift.io/type: kubernetes
  name: simple-quarkus-service-gitops
spec:
  params:
    - default: simple-quarkus-service
      name: APP_NAME
      type: string
    - default: 'https://github.com/froberge/simple-quarkus-service'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: 'https://github.com/froberge/simple-quarkus-service-deploy'
      name: DEPLOY_GIT_REPO
      type: string
    - default: main
      name: DEPLOY_GIT_REVISION
      type: string
    - default: gitops-demo/simple-quarkus-service-deploy/app/overlays/dev
      name: DEV_OVERLAY_DIR
      type: string
    - default: gitops-demo/simple-quarkus-service-deploy/app/overlays/prod
      name: PROD_OVERLAY_DIR
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/simple-quarkus-pipeline/simple-quarkus-service
      name: IMAGE_NAME
      type: string
    - default: openjdk-11-el7
      name: VERSION
      type: string
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: create-image-tag
      params:
        - name: commit
          value: $(tasks.clone-repository.results.commit)
        - name: url
          value: $(tasks.clone-repository.results.url)
        - name: imagestream
          value: $(params.IMAGE_NAME)
      taskRef:
        name: set-image-tag
      runAfter:
        - clone-repository
      workspaces:
      - name: tagoutput
        workspace: source
    - name: test-app
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
        - clone-repository
      params:
        - name: GOALS
          value:
            - 'clean'
            - 'test'
      workspaces:
        - name: maven-settings
          workspace: m2-repo
        - name: source
          workspace: source
    - name: build
      params:
        - name: IMAGE
          value: $(tasks.create-image-tag.results.tag)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(workspaces.source.path)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - test-app
        - create-image-tag
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: source
    - name: clone-deployment-repo
      params:
      - name: url
        value: $(params.DEPLOY_GIT_REPO)
      - name: revision
        value: $(params.DEPLOY_GIT_REVISION)
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - build
      workspaces:
      - name: output
        workspace: source
    - name: patch-dev
      taskRef:
        name: kustomize
      params:
        - name: imagestream
          value: $(tasks.create-image-tag.results.tag)
        - name: overlaypath
          value: $(params.DEV_OVERLAY_DIR)
      runAfter:
        - clone-deployment-repo
      workspaces:
        - name: source
          workspace: source
    - name: commit-to-dev
      params:
      - name: GIT_USER_NAME
        value: simple-quarkus-pipeline-bot
      - name: GIT_USER_EMAIL
        value: simple-quarkus-pipeline-bot@demo.com
      - name: GIT_SCRIPT
        value: |
          git add -A .
          git commit -am "Run $(tasks.create-image-tag.results.tagref): Updating image to $(tasks.create-image-tag.results.tag) on $(params.DEV_OVERLAY_DIR)"
          git push origin HEAD:main
      taskRef:
        name: git-cli
        kind: ClusterTask
      runAfter:
        - patch-dev
      workspaces:
      - name: source
        workspace: source
      - name: input
        workspace: scratch
  workspaces:
    - name: source
    - name: m2-repo
    - name: scratch
      description: This is a scratch disk

